name: CI — Tests


on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Ensure pip is up to date
        run: python -m pip install --upgrade pip

      - name: Install project (editable) and test deps
        # If you have requirements.txt use pip install -r requirements.txt
        run: |
          pip install -r requirements.txt
          python -m pip install -e .

      - name: Run tests with pytest
        run: python -m pytest -v

      - name: Upload pytest results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: .pytest_cache || /dev/null
